apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lingualeap.fullname" . }}-frontend
  labels:
    {{- include "lingualeap.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount.frontend }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lingualeap.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lingualeap.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lingualeap.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.frontend.name }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.frontend.targetPort }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.config.nodeEnv }}
            - name: NEXT_PUBLIC_API_URL
              value: "{{ .Values.config.clientUrl }}/api"
          {{- if .Values.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.frontend.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthCheck.frontend.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.frontend.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.frontend.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthCheck.frontend.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.frontend.periodSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}