{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lingualeap.fullname" . }}-mongodb
  labels:
    {{- include "lingualeap.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
  selector:
    {{- include "lingualeap.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
{{- end }}
