{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lingualeap.fullname" . }}-secrets
  labels:
    {{- include "lingualeap.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-uri: {{ printf "mongodb://%s:%s@%s-mongodb:27017/%s?authSource=admin" .Values.mongodb.auth.username .Values.mongodb.auth.password (include "lingualeap.fullname" .) .Values.mongodb.auth.database | b64enc }}
  jwt-secret: {{ .Values.config.jwtSecret | b64enc }}
  google-genai-api-key: {{ .Values.config.googleGenaiApiKey | default "" | b64enc | quote }}
  smtp-host: {{ .Values.config.smtp.host | b64enc }}
  smtp-port: {{ .Values.config.smtp.port | toString | b64enc }}
  smtp-secure: {{ .Values.config.smtp.secure | toString | b64enc }}
  smtp-user: {{ .Values.config.smtp.user | b64enc }}
  smtp-password: {{ .Values.config.smtp.password | b64enc }}
{{- end }}