apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lingualeap.fullname" . }}-secrets
  labels:
    {{- include "lingualeap.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-uri: {{ printf "mongodb://%s:%s@%s-mongodb:27017/%s" .Values.mongodb.auth.username .Values.mongodb.auth.password (include "lingualeap.fullname" .) .Values.mongodb.auth.database | b64enc }}
  jwt-secret: {{ .Values.config.jwtSecret | b64enc }}
  smtp-password: {{ .Values.config.smtp.password | b64enc }}