apiVersion: v1
kind: Service
metadata:
  name: {{ include "lingualeap.fullname" . }}-frontend
  labels:
    {{- include "lingualeap.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lingualeap.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lingualeap.fullname" . }}-backend
  labels:
    {{- include "lingualeap.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lingualeap.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend